"use client";

import { useEffect, useRef } from "react";
import maplibregl from "maplibre-gl";
import { cx } from "../../lib/cx.js";
import { formatVnd } from "../../lib/booking.js";

// Clean, minimalist basemap (vector). Self-hosted style generated by
// `scripts/build-map-style.mjs` — OpenFreeMap's Positron recolored to a pastel
// green / pastel blue / grey Waze-style palette. Vector tiles, fonts and sprites
// are still served by OpenFreeMap (free, keyless); only the colors are ours.
const STYLE_URL = "/map/washgo-style.json";

// MapLibre uses [lng, lat] order (the opposite of Leaflet's [lat, lng]).
const DEFAULT_CENTER = [106.7305, 10.7995];

// MapLibre positions markers purely with an inline `transform`, but that only
// pins them to the map if the element is `position:absolute` at the canvas
// origin — a rule that lives in `maplibre-gl.css`. If that stylesheet fails to
// apply (e.g. a stale dev build serving a 404 CSS chunk), markers fall back to
// `position:static` and stack in document flow: every pin picks up a constant
// `index x height` offset, so they slide on zoom and collapse into an evenly
// spaced vertical line when zoomed out. Setting the critical bits inline makes
// the markers self-sufficient regardless of whether the stylesheet loads.
function applyMarkerBaseStyle(el) {
  el.style.position = "absolute";
  el.style.top = "0";
  el.style.left = "0";
  el.style.willChange = "transform";
}

// Pin palette (mirrors Tailwind `wash-500` / `wash-700`).
const PIN_COLOR = "#ef3124";
const PIN_COLOR_ACTIVE = "#b81c12";

// Inline car glyph (lucide "car"), drawn white inside the price bubble.
const CAR_ICON =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
  '<path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3' +
  'c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"/>' +
  '<circle cx="7" cy="17" r="2"/><path d="M9 17h6"/><circle cx="17" cy="17" r="2"/></svg>';

// Marker visuals live in a runtime-injected stylesheet (created by THIS module,
// not the bundled CSS) so they survive a stale build that fails to serve the
// app's CSS chunk — the same reason the critical positioning is set inline.
let pinStylesInjected = false;
function ensurePinStyles() {
  if (pinStylesInjected || typeof document === "undefined") return;
  pinStylesInjected = true;
  const style = document.createElement("style");
  style.id = "wg-pin-styles";
  style.textContent = [
    // inline-flex => the marker root shrinks to its content, so anchor "bottom"
    // anchors the pointer tip (not the full-width container).
    ".wg-pin{display:inline-flex;cursor:pointer}",
    ".wg-pin__inner{display:flex;flex-direction:column;align-items:center;transform-origin:bottom center;transition:transform .12s ease;will-change:transform}",
    `.wg-pin__bubble{display:flex;align-items:center;gap:4px;padding:4px 9px 4px 7px;border-radius:9999px;background:${PIN_COLOR};color:#fff;border:2px solid #fff;box-shadow:0 2px 6px rgba(0,0,0,.3);font:700 12px/1 Aptos,"Segoe UI",sans-serif;white-space:nowrap}`,
    ".wg-pin__bubble svg{width:15px;height:15px;display:block;flex:none}",
    // pointer built from real layout boxes so the element's box-bottom IS the
    // visual tip (no empty padding below it). ::before = white outline.
    ".wg-pin__tip{position:relative;width:16px;height:9px;margin-top:-1px}",
    '.wg-pin__tip::before{content:"";position:absolute;left:0;top:0;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:9px solid #fff}',
    `.wg-pin__tip::after{content:"";position:absolute;left:2px;top:0;width:0;height:0;border-left:6px solid transparent;border-right:6px solid transparent;border-top:7px solid ${PIN_COLOR}}`,
    ".wg-pin--active{z-index:1}",
    ".wg-pin--active .wg-pin__inner{transform:scale(1.16)}",
    `.wg-pin--active .wg-pin__bubble{background:${PIN_COLOR_ACTIVE}}`,
    `.wg-pin--active .wg-pin__tip::after{border-top-color:${PIN_COLOR_ACTIVE}}`
  ].join("\n");
  document.head.appendChild(style);
}

// Build a car-wash pin: a rounded bubble with the car glyph + starting price and
// a pointer whose tip sits exactly on the shop coordinate (anchor "bottom").
// The pointer is built from real layout boxes (not a transformed/oversized SVG),
// so the element's box-bottom IS the visual tip — that's what keeps the pin from
// appearing to drift against the map (the old SVG had ~5px of empty space below
// its tip, see the StackOverflow thread on markers "moving" on zoom).
function createPinElement(priceText, active) {
  ensurePinStyles();
  const el = document.createElement("div");
  el.className = active ? "wg-pin wg-pin--active" : "wg-pin";
  applyMarkerBaseStyle(el);

  const inner = document.createElement("div");
  inner.className = "wg-pin__inner";

  const bubble = document.createElement("div");
  bubble.className = "wg-pin__bubble";
  bubble.innerHTML = CAR_ICON;
  if (priceText) {
    const price = document.createElement("span");
    price.textContent = priceText;
    bubble.appendChild(price);
  }

  const tip = document.createElement("div");
  tip.className = "wg-pin__tip";

  inner.append(bubble, tip);
  el.appendChild(inner);
  return el;
}

// Toggle the enlarged/highlighted "selected" treatment without rebuilding.
function setPinActive(el, active) {
  if (el) el.classList.toggle("wg-pin--active", active);
}

// Build the blue "you are here" puck element.
function createUserElement() {
  const el = document.createElement("span");
  el.style.cssText =
    "display:block;width:18px;height:18px;border-radius:9999px;" +
    "background:#2f7df6;border:3px solid #fff;" +
    "box-shadow:0 0 0 6px rgba(47,125,246,0.25),0 1px 4px rgba(0,0,0,0.3)";
  applyMarkerBaseStyle(el);
  return el;
}

/**
 * Interactive, pannable/zoomable MapLibre map with a marker per car wash and a
 * "you are here" puck. Clicking a marker calls `onSelectShop(shop.id)`.
 */
export function InteractiveMap({
  shops = [],
  selectedId = null,
  onSelectShop,
  onPick,
  userLocation,
  className,
  rounded = "rounded-none",
  interactive = true
}) {
  const containerRef = useRef(null);
  const mapRef = useRef(null);
  const markersRef = useRef({});
  const selectRef = useRef(onSelectShop);
  selectRef.current = onSelectShop;
  // Optional location-picker callback (owner shop form). Mirrored in a ref so the
  // once-only init effect can read the latest handler without re-initialising.
  const pickRef = useRef(onPick);
  pickRef.current = onPick;
  // Mirror the latest props in refs so the marker-build / flyTo effects can read
  // them without listing `shops` as a dependency (it's a fresh array each render).
  const selectedIdRef = useRef(selectedId);
  selectedIdRef.current = selectedId;
  const shopsRef = useRef(shops);
  shopsRef.current = shops;

  // Init the map once.
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return undefined;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: STYLE_URL,
      center: userLocation ? [userLocation.lng, userLocation.lat] : DEFAULT_CENTER,
      zoom: 14,
      attributionControl: interactive ? { compact: true } : false,
      // Preview maps (home page) are static, click-through snapshots.
      interactive
    });

    if (interactive) {
      map.addControl(
        new maplibregl.NavigationControl({ showCompass: false, showZoom: true }),
        "bottom-right"
      );
    }

    if (userLocation) {
      new maplibregl.Marker({ element: createUserElement(), anchor: "center", subpixelPositioning: true })
        .setLngLat([userLocation.lng, userLocation.lat])
        .addTo(map);
    }

    // Location picker: clicking anywhere reports the dropped coordinate. The
    // caller renders the picked point back as a single shop pin via `shops`.
    map.on("click", (event) => {
      pickRef.current?.(event.lngLat.lat, event.lngLat.lng);
    });

    mapRef.current = map;
    if (typeof window !== "undefined") window.__wgmap = map; // TEMP debug probe
    // Containers that mount during a layout/transition can mis-measure; nudge.
    const raf = window.requestAnimationFrame(() => map.resize());

    const observer = typeof ResizeObserver !== "undefined"
      ? new ResizeObserver(() => map.resize())
      : null;
    if (observer) observer.observe(containerRef.current);

    // Markers are positioned from the map's measured geometry. On mobile the URL
    // bar collapses as the page scrolls, which changes the visual viewport and
    // shifts the container WITHOUT a size change the ResizeObserver would catch —
    // so the pins visibly drift. Re-measure on scroll / viewport changes
    // (rAF-throttled) to keep them pinned. Capture phase catches inner scrollers.
    let scheduled = false;
    const nudgeResize = () => {
      if (scheduled) return;
      scheduled = true;
      window.requestAnimationFrame(() => {
        scheduled = false;
        if (mapRef.current) mapRef.current.resize();
      });
    };
    window.addEventListener("scroll", nudgeResize, { passive: true, capture: true });
    window.addEventListener("resize", nudgeResize, { passive: true });
    const vv = window.visualViewport;
    vv?.addEventListener("resize", nudgeResize, { passive: true });
    vv?.addEventListener("scroll", nudgeResize, { passive: true });

    return () => {
      window.cancelAnimationFrame(raf);
      if (observer) observer.disconnect();
      window.removeEventListener("scroll", nudgeResize, { capture: true });
      window.removeEventListener("resize", nudgeResize);
      vv?.removeEventListener("resize", nudgeResize);
      vv?.removeEventListener("scroll", nudgeResize);
      map.remove();
      mapRef.current = null;
      markersRef.current = {};
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Diff shop markers when the visible set changes: reuse existing markers, add
  // only new shops, remove only departed ones. Avoids tearing down every pin on
  // each search keystroke (which caused visible flicker).
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    const nextIds = new Set();
    shops.forEach((shop) => {
      if (shop.lat == null || shop.lng == null) return;
      nextIds.add(shop.id);

      const existing = markersRef.current[shop.id];
      if (existing) {
        existing.setLngLat([shop.lng, shop.lat]);
        return;
      }

      const priceText = shop.starting != null ? formatVnd(shop.starting) : "";
      const el = createPinElement(priceText, shop.id === selectedIdRef.current);
      el.addEventListener("click", (event) => {
        event.stopPropagation();
        selectRef.current?.(shop.id);
      });
      const marker = new maplibregl.Marker({ element: el, anchor: "bottom", subpixelPositioning: true })
        .setLngLat([shop.lng, shop.lat])
        .addTo(map);
      markersRef.current[shop.id] = marker;
    });

    Object.keys(markersRef.current).forEach((id) => {
      if (!nextIds.has(id)) {
        markersRef.current[id].remove();
        delete markersRef.current[id];
      }
    });
  }, [shops]);

  // Enlarge/highlight the active pin in place when the selection changes — no
  // marker churn. The scale lives on an inner element (transform-origin bottom
  // center) so the pointer tip stays anchored to the coordinate.
  useEffect(() => {
    Object.entries(markersRef.current).forEach(([id, marker]) => {
      setPinActive(marker.getElement(), id === selectedId);
    });
  }, [selectedId]);

  // Pan/zoom to the selected shop (reads shops via ref so panning + typing don't
  // re-center an already-selected pin).
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !selectedId) return;
    const shop = shopsRef.current.find((item) => item.id === selectedId);
    if (shop?.lat != null) {
      map.flyTo({
        center: [shop.lng, shop.lat],
        zoom: Math.max(map.getZoom(), 15)
      });
    }
  }, [selectedId]);

  return (
    <div
      ref={containerRef}
      className={cx("isolate bg-[#e4eef0]", !interactive && "pointer-events-none", rounded, className)}
    />
  );
}
