"use client";

import { useEffect, useRef } from "react";
import maplibregl from "maplibre-gl";
import { icons } from "../../assets.js";
import { cx } from "../../lib/cx.js";

// Clean, minimalist basemap (vector). Self-hosted style generated by
// `scripts/build-map-style.mjs` — OpenFreeMap's Positron recolored to a pastel
// green / pastel blue / grey Waze-style palette. Vector tiles, fonts and sprites
// are still served by OpenFreeMap (free, keyless); only the colors are ours.
const STYLE_URL = "/map/washgo-style.json";

// MapLibre uses [lng, lat] order (the opposite of Leaflet's [lat, lng]).
const DEFAULT_CENTER = [106.7305, 10.7995];

// Build the DOM element for a car-wash pin marker. MapLibre markers are plain
// HTML elements; the "active" variant (selected shop) is rendered larger.
function createPinElement(active) {
  const size = active ? 54 : 40;
  const el = document.createElement("img");
  el.src = icons.mapCarPin;
  el.width = size;
  el.height = size;
  el.alt = "";
  el.draggable = false;
  el.className = active ? "wg-marker wg-marker--active" : "wg-marker";
  el.style.cursor = "pointer";
  el.style.display = "block";
  return el;
}

// Build the blue "you are here" puck element.
function createUserElement() {
  const el = document.createElement("span");
  el.style.cssText =
    "display:block;width:18px;height:18px;border-radius:9999px;" +
    "background:#2f7df6;border:3px solid #fff;" +
    "box-shadow:0 0 0 6px rgba(47,125,246,0.25),0 1px 4px rgba(0,0,0,0.3)";
  return el;
}

/**
 * Interactive, pannable/zoomable MapLibre map with a marker per car wash and a
 * "you are here" puck. Clicking a marker calls `onSelectShop(shop.id)`.
 */
export function InteractiveMap({
  shops = [],
  selectedId = null,
  onSelectShop,
  userLocation,
  className,
  rounded = "rounded-none",
  interactive = true
}) {
  const containerRef = useRef(null);
  const mapRef = useRef(null);
  const markersRef = useRef({});
  const selectRef = useRef(onSelectShop);
  selectRef.current = onSelectShop;

  // Init the map once.
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return undefined;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: STYLE_URL,
      center: userLocation ? [userLocation.lng, userLocation.lat] : DEFAULT_CENTER,
      zoom: 14,
      attributionControl: interactive ? { compact: true } : false,
      // Preview maps (home page) are static, click-through snapshots.
      interactive
    });

    if (interactive) {
      map.addControl(
        new maplibregl.NavigationControl({ showCompass: false, showZoom: true }),
        "bottom-right"
      );
    }

    if (userLocation) {
      new maplibregl.Marker({ element: createUserElement(), anchor: "center" })
        .setLngLat([userLocation.lng, userLocation.lat])
        .addTo(map);
    }

    mapRef.current = map;
    // Containers that mount during a layout/transition can mis-measure; nudge.
    const raf = window.requestAnimationFrame(() => map.resize());

    const observer = typeof ResizeObserver !== "undefined"
      ? new ResizeObserver(() => map.resize())
      : null;
    if (observer) observer.observe(containerRef.current);

    return () => {
      window.cancelAnimationFrame(raf);
      if (observer) observer.disconnect();
      map.remove();
      mapRef.current = null;
      markersRef.current = {};
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // (Re)build shop markers when the visible set (or selection) changes.
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    Object.values(markersRef.current).forEach((marker) => marker.remove());
    markersRef.current = {};

    shops.forEach((shop) => {
      if (shop.lat == null || shop.lng == null) return;
      const el = createPinElement(shop.id === selectedId);
      el.addEventListener("click", (event) => {
        event.stopPropagation();
        selectRef.current?.(shop.id);
      });
      const marker = new maplibregl.Marker({ element: el, anchor: "bottom" })
        .setLngLat([shop.lng, shop.lat])
        .addTo(map);
      markersRef.current[shop.id] = marker;
    });
  }, [shops, selectedId]);

  // Pan/zoom to the selected shop.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !selectedId) return;
    const shop = shops.find((item) => item.id === selectedId);
    if (shop?.lat != null) {
      map.flyTo({
        center: [shop.lng, shop.lat],
        zoom: Math.max(map.getZoom(), 15)
      });
    }
  }, [selectedId, shops]);

  return (
    <div
      ref={containerRef}
      className={cx("isolate bg-[#e4eef0]", !interactive && "pointer-events-none", rounded, className)}
    />
  );
}
