"use client";

import { useEffect, useRef } from "react";
import maplibregl from "maplibre-gl";
import { icons } from "../../assets.js";
import { cx } from "../../lib/cx.js";

// Clean, minimalist basemap (vector). Self-hosted style generated by
// `scripts/build-map-style.mjs` — OpenFreeMap's Positron recolored to a pastel
// green / pastel blue / grey Waze-style palette. Vector tiles, fonts and sprites
// are still served by OpenFreeMap (free, keyless); only the colors are ours.
const STYLE_URL = "/map/washgo-style.json";

// MapLibre uses [lng, lat] order (the opposite of Leaflet's [lat, lng]).
const DEFAULT_CENTER = [106.7305, 10.7995];

// Build the DOM element for a car-wash pin marker. MapLibre markers are plain
// HTML elements; the "active" variant (selected shop) is rendered larger.
function createPinElement(active) {
  const size = active ? 54 : 40;
  const el = document.createElement("img");
  el.src = icons.mapCarPin;
  el.width = size;
  el.height = size;
  el.alt = "";
  el.draggable = false;
  el.className = active ? "wg-marker wg-marker--active" : "wg-marker";
  el.style.cursor = "pointer";
  el.style.display = "block";
  return el;
}

// Build the blue "you are here" puck element.
function createUserElement() {
  const el = document.createElement("span");
  el.style.cssText =
    "display:block;width:18px;height:18px;border-radius:9999px;" +
    "background:#2f7df6;border:3px solid #fff;" +
    "box-shadow:0 0 0 6px rgba(47,125,246,0.25),0 1px 4px rgba(0,0,0,0.3)";
  return el;
}

/**
 * Interactive, pannable/zoomable MapLibre map with a marker per car wash and a
 * "you are here" puck. Clicking a marker calls `onSelectShop(shop.id)`.
 */
export function InteractiveMap({
  shops = [],
  selectedId = null,
  onSelectShop,
  onPick,
  userLocation,
  className,
  rounded = "rounded-none",
  interactive = true
}) {
  const containerRef = useRef(null);
  const mapRef = useRef(null);
  const markersRef = useRef({});
  const selectRef = useRef(onSelectShop);
  selectRef.current = onSelectShop;
  // Optional location-picker callback (owner shop form). Mirrored in a ref so the
  // once-only init effect can read the latest handler without re-initialising.
  const pickRef = useRef(onPick);
  pickRef.current = onPick;
  // Mirror the latest props in refs so the marker-build / flyTo effects can read
  // them without listing `shops` as a dependency (it's a fresh array each render).
  const selectedIdRef = useRef(selectedId);
  selectedIdRef.current = selectedId;
  const shopsRef = useRef(shops);
  shopsRef.current = shops;

  // Init the map once.
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return undefined;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: STYLE_URL,
      center: userLocation ? [userLocation.lng, userLocation.lat] : DEFAULT_CENTER,
      zoom: 14,
      attributionControl: interactive ? { compact: true } : false,
      // Preview maps (home page) are static, click-through snapshots.
      interactive
    });

    if (interactive) {
      map.addControl(
        new maplibregl.NavigationControl({ showCompass: false, showZoom: true }),
        "bottom-right"
      );
    }

    if (userLocation) {
      new maplibregl.Marker({ element: createUserElement(), anchor: "center" })
        .setLngLat([userLocation.lng, userLocation.lat])
        .addTo(map);
    }

    // Location picker: clicking anywhere reports the dropped coordinate. The
    // caller renders the picked point back as a single shop pin via `shops`.
    map.on("click", (event) => {
      pickRef.current?.(event.lngLat.lat, event.lngLat.lng);
    });

    mapRef.current = map;
    // Containers that mount during a layout/transition can mis-measure; nudge.
    const raf = window.requestAnimationFrame(() => map.resize());

    const observer = typeof ResizeObserver !== "undefined"
      ? new ResizeObserver(() => map.resize())
      : null;
    if (observer) observer.observe(containerRef.current);

    return () => {
      window.cancelAnimationFrame(raf);
      if (observer) observer.disconnect();
      map.remove();
      mapRef.current = null;
      markersRef.current = {};
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Diff shop markers when the visible set changes: reuse existing markers, add
  // only new shops, remove only departed ones. Avoids tearing down every pin on
  // each search keystroke (which caused visible flicker).
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    const nextIds = new Set();
    shops.forEach((shop) => {
      if (shop.lat == null || shop.lng == null) return;
      nextIds.add(shop.id);

      const existing = markersRef.current[shop.id];
      if (existing) {
        existing.setLngLat([shop.lng, shop.lat]);
        return;
      }

      const el = createPinElement(shop.id === selectedIdRef.current);
      el.addEventListener("click", (event) => {
        event.stopPropagation();
        selectRef.current?.(shop.id);
      });
      const marker = new maplibregl.Marker({ element: el, anchor: "bottom" })
        .setLngLat([shop.lng, shop.lat])
        .addTo(map);
      markersRef.current[shop.id] = marker;
    });

    Object.keys(markersRef.current).forEach((id) => {
      if (!nextIds.has(id)) {
        markersRef.current[id].remove();
        delete markersRef.current[id];
      }
    });
  }, [shops]);

  // Resize the active pin in place when the selection changes — no marker churn.
  useEffect(() => {
    Object.entries(markersRef.current).forEach(([id, marker]) => {
      const el = marker.getElement();
      if (!el) return;
      const active = id === selectedId;
      const size = active ? 54 : 40;
      el.width = size;
      el.height = size;
      el.className = active ? "wg-marker wg-marker--active" : "wg-marker";
    });
  }, [selectedId]);

  // Pan/zoom to the selected shop (reads shops via ref so panning + typing don't
  // re-center an already-selected pin).
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !selectedId) return;
    const shop = shopsRef.current.find((item) => item.id === selectedId);
    if (shop?.lat != null) {
      map.flyTo({
        center: [shop.lng, shop.lat],
        zoom: Math.max(map.getZoom(), 15)
      });
    }
  }, [selectedId]);

  return (
    <div
      ref={containerRef}
      className={cx("isolate bg-[#e4eef0]", !interactive && "pointer-events-none", rounded, className)}
    />
  );
}
